### ISSUE TITLE
*** RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by YangjiaqiDig** [zhaozhengChen/ReCAM#12]
Hey, just as the title. Have you ever saw such error? 
The issue happened with recam_predictor to cuda, and the model also dataparallel to cuda.
After I  run recam_predictor on CPU, it works.

Is that because my torch cuda version?
I installed your env, but my nvidia is NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1 
So I changed the env to 10.1

**Comment by zhaozhengChen** [comment]
Sorry, I didn't encounter this problem.

**Comment by YangjiaqiDig** [comment]
> Sorry, I didn't encounter this problem.

Okay, thanks. i solved it by using CPU instead and turn the result back to cuda device again later
